// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skuld.DataSync;

namespace Skuld.DataSync.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20180615141549_dbupgrade")]
    partial class dbupgrade
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SF.Sys.Data.IdentGenerator.DataModels.IdentSeed", b =>
                {
                    b.Property<string>("Type")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200);

                    b.Property<long>("NextValue");

                    b.Property<int>("Section");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Type");

                    b.ToTable("SysIdentSeed");
                });

            modelBuilder.Entity("SF.Sys.Reminders.DataModels.DataReminder", b =>
                {
                    b.Property<long>("Id");

                    b.Property<long>("BizIdent");

                    b.Property<string>("BizIdentType");

                    b.Property<string>("BizType");

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("Data")
                        .HasMaxLength(1000);

                    b.Property<string>("InternalRemarks");

                    b.Property<byte>("LogicState");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long?>("OwnerId");

                    b.Property<string>("RemindableName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long?>("ServiceDataScopeId");

                    b.Property<int>("TaskExecCount");

                    b.Property<DateTime?>("TaskLastExecTime");

                    b.Property<string>("TaskMessage");

                    b.Property<DateTime?>("TaskNextExecTime");

                    b.Property<DateTime?>("TaskStartTime");

                    b.Property<int>("TaskState");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("UpdatedTime");

                    b.Property<long?>("UpdatorId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ServiceDataScopeId");

                    b.HasIndex("UpdatorId");

                    b.HasIndex("TaskState", "TaskNextExecTime");

                    b.HasIndex("BizType", "BizIdentType", "BizIdent")
                        .IsUnique()
                        .HasFilter("[BizType] IS NOT NULL AND [BizIdentType] IS NOT NULL");

                    b.ToTable("SysReminder");
                });

            modelBuilder.Entity("SF.Sys.Reminders.DataModels.DataRemindRecord", b =>
                {
                    b.Property<long>("Id");

                    b.Property<long>("BizIdent");

                    b.Property<string>("BizIdentType");

                    b.Property<string>("BizType");

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("Data")
                        .HasMaxLength(1000);

                    b.Property<string>("InternalRemarks");

                    b.Property<byte>("LogicState");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long?>("OwnerId");

                    b.Property<string>("RemindableName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long?>("ServiceDataScopeId");

                    b.Property<int>("TaskExecCount");

                    b.Property<DateTime?>("TaskLastExecTime");

                    b.Property<string>("TaskMessage");

                    b.Property<DateTime?>("TaskNextExecTime");

                    b.Property<DateTime?>("TaskStartTime");

                    b.Property<int>("TaskState");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<DateTime>("UpdatedTime");

                    b.Property<long?>("UpdatorId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ServiceDataScopeId");

                    b.HasIndex("UpdatorId");

                    b.HasIndex("TaskState", "TaskNextExecTime");

                    b.HasIndex("BizType", "BizIdentType", "BizIdent");

                    b.ToTable("SysRemindRecord");
                });

            modelBuilder.Entity("SF.Sys.Services.Management.DataModels.DataServiceInstance", b =>
                {
                    b.Property<long>("Id");

                    b.Property<long?>("ContainerId");

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<string>("Icon")
                        .HasMaxLength(100);

                    b.Property<string>("Image")
                        .HasMaxLength(100);

                    b.Property<string>("ImplementId")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("ImplementType")
                        .IsRequired();

                    b.Property<string>("InternalRemarks");

                    b.Property<int>("ItemOrder");

                    b.Property<byte>("LogicState");

                    b.Property<string>("Memo")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long?>("OwnerId");

                    b.Property<string>("Remarks")
                        .HasMaxLength(100);

                    b.Property<long?>("ServiceDataScopeId");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("ServiceIdent")
                        .HasMaxLength(200);

                    b.Property<string>("ServiceType")
                        .IsRequired();

                    b.Property<string>("Setting");

                    b.Property<string>("SubTitle")
                        .HasMaxLength(100);

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedTime");

                    b.Property<long?>("UpdatorId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("ImplementId");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ServiceDataScopeId");

                    b.HasIndex("ServiceIdent");

                    b.HasIndex("UpdatorId");

                    b.HasIndex("ContainerId", "ItemOrder");

                    b.HasIndex("ContainerId", "ServiceId");

                    b.ToTable("SysServiceInstance");
                });

            modelBuilder.Entity("Skuld.DataStorages.Entity.Models.Category", b =>
                {
                    b.Property<string>("Type")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Type", "Name");

                    b.ToTable("SkuldCategories");
                });

            modelBuilder.Entity("Skuld.DataStorages.Entity.Models.CategorySymbol", b =>
                {
                    b.Property<string>("Type")
                        .HasMaxLength(100);

                    b.Property<string>("Category")
                        .HasMaxLength(100);

                    b.Property<string>("Symbol")
                        .HasMaxLength(100);

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Type", "Category", "Symbol");

                    b.HasIndex("Type", "Symbol");

                    b.ToTable("SkuldCategorySymbols");
                });

            modelBuilder.Entity("Skuld.DataStorages.Entity.Models.CategoryType", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Name");

                    b.ToTable("SkuldCategoryTypes");
                });

            modelBuilder.Entity("Skuld.DataStorages.Entity.Models.Price", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20);

                    b.Property<int>("Interval");

                    b.Property<DateTime>("Time");

                    b.Property<float>("AdjustRate");

                    b.Property<float>("Close");

                    b.Property<float>("High");

                    b.Property<float>("Low");

                    b.Property<float>("Open");

                    b.Property<float>("Volume");

                    b.HasKey("Symbol", "Interval", "Time");

                    b.ToTable("SkuldPrices");
                });

            modelBuilder.Entity("Skuld.DataStorages.Entity.Models.PropertyGroup", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Name");

                    b.ToTable("SkuldPropertyGroups");
                });

            modelBuilder.Entity("Skuld.DataStorages.Entity.Models.PropertyItem", b =>
                {
                    b.Property<string>("Group")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Group", "Name");

                    b.ToTable("SkuldPropertyItems");
                });

            modelBuilder.Entity("Skuld.DataStorages.Entity.Models.Symbol", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ScopeCode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("SkuldSymbols");
                });

            modelBuilder.Entity("Skuld.DataStorages.Entity.Models.SymbolPropertyGroup", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20);

                    b.Property<string>("Group")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("NextUpdateTime");

                    b.Property<int>("RowCount");

                    b.Property<DateTime>("Time");

                    b.HasKey("Symbol", "Group");

                    b.ToTable("SkuldSymbolPropertyGroups");
                });

            modelBuilder.Entity("Skuld.DataStorages.Entity.Models.SymbolPropertyGroupHistory", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20);

                    b.Property<string>("Group")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Time");

                    b.Property<int>("RowCount");

                    b.HasKey("Symbol", "Group", "Time");

                    b.ToTable("SkuldSymbolPropertyGroupHistories");
                });

            modelBuilder.Entity("Skuld.DataStorages.Entity.Models.SymbolPropertyValue", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20);

                    b.Property<string>("Group")
                        .HasMaxLength(50);

                    b.Property<string>("Property")
                        .HasMaxLength(50);

                    b.Property<int>("Row");

                    b.Property<double?>("Number");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("Symbol", "Group", "Property", "Row");

                    b.ToTable("SkuldSymbolPropertyValues");
                });

            modelBuilder.Entity("Skuld.DataStorages.Entity.Models.SymbolPropertyValueHistory", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20);

                    b.Property<string>("Group")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Time");

                    b.Property<string>("Property")
                        .HasMaxLength(50);

                    b.Property<int>("Row");

                    b.Property<double?>("Number");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("Symbol", "Group", "Time", "Property", "Row");

                    b.ToTable("SkuldSymbolPropertyValueHistories");
                });

            modelBuilder.Entity("SF.Sys.Services.Management.DataModels.DataServiceInstance", b =>
                {
                    b.HasOne("SF.Sys.Services.Management.DataModels.DataServiceInstance", "Container")
                        .WithMany("Children")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
